### ISSUE TITLE
some inconsistences

### ISSUE THREAD

**Issue by dicotom** [JacoMoolman/GenLot#1]
$NumberOfNumbersInLotto be 7 instead of 6?
$Mutation shouldn't be a value between 0 and 10, and not 49?
How is the variable value $PopulationNumerY chosen?
How is the variable value $MaxMutationValue chosen?
Shouldn't the line, $number=Get-Random -Maximum 50 -Minimum 1 be
$number=Get-Random -Maximum 53 -Minimum 1?

**Comment by JacoMoolman** [comment]
Hey there. Thanks so much for looking at this code. I did this about 3.5 years ago so can not remember all the details. 
Feel free to play with it and send me a PR if you wish.
